services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - db_data:/data/db

volumes:
  db_data:
